version: '3.4'

services:
  eo-web-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=${DATABASE_CONNECTION}
      - WebOptions__Authority=${DOCKER_DOMAIN}:${AUTHORITY_PORT}
      - WebOptions__WebClient=${LOCAL_DOMAIN}:${WEB_CLIENT_PORT}
      - WebOptions__SchedulerClient=${DOCKER_DOMAIN}:${SCHEDULER_PORT}
      - WebOptions__UseCustomSslCertificates=true
    ports:
      - 5100:80
      - ${WEB_API_PORT}:443
    volumes:
      - ./src:/app/certificates

  eo-identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - UseCustomSslCertificates=true
      - AllowedOrigins__WebClient=${LOCAL_DOMAIN}:${WEB_CLIENT_PORT}
      - AllowedOrigins__WebApi=${DOCKER_DOMAIN}:${WEB_API_PORT}
      - AllowedOrigins__SchedulerClient=${DOCKER_DOMAIN}:${SCHEDULER_PORT}
    ports:
      - 5101:80
      - ${AUTHORITY_PORT}:443
    volumes:
      - ./src:/app/certificates

  eo-scheduler:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=${DATABASE_CONNECTION}
      - Authority=${DOCKER_DOMAIN}:${AUTHORITY_PORT}
      - UseCustomSslCertificates=true
    ports:
      - "5102:80"
      - "${SCHEDULER_PORT}:443"
    volumes:
      - ./src:/app/certificates

  eo-web-client :
    build:
      context: .
    environment:
      - REACT_APP_WEB_CLIENT_URL=${LOCAL_DOMAIN}:${WEB_CLIENT_PORT}
      - REACT_APP_WEB_API_URL=${DOCKER_DOMAIN}:${WEB_API_PORT}
      - REACT_APP_IDENTITY_SERVER_URL=${DOCKER_DOMAIN}:${AUTHORITY_PORT}
    ports:
      - ${WEB_CLIENT_PORT}:3000

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd
    ports:
      - "3307:3306"
