name: .Net Deploy

on:
  workflow_call:
    inputs:
      application_name:
        required: true
        type: string
      environment_name:
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    name: CI Deploy
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: app_build

    - name: Zip Package
      run: |
        cd ${{ github.workspace }}/out 
        zip -r ${{ github.workspace }}/out.zip *

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ inputs.application_name }}
        environment_name: ${{ inputs.environment_name }}
        region: eu-north-1
        version_label: ${{ github.run_id }}
        version_description: ${{ github.sha }}
        deployment_package: ${{ github.workspace }}/out.zip
