name: AWS Elastic Beanstalk Push

on:
  workflow_call:
    inputs:
      application_name:
        required: true
        type: string
      environment_name:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ inputs.application_name }}
          environment_name: ${{ inputs.environment_name }}
          version_label: ${{ github.sha }}
          existing_bucket_name: elasticbeanstalk-eu-north-1-386274526447
          region: eu-north-1
          deployment_package: deploy.zip
