name: Docker Build|Push

on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: true
        type: string
      docker_repository_name:
        required: true
        type: string
      push:
        description: Push to Docker Hub
        type: boolean
        required: false
        default: false
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build_docker:
    runs-on: ubuntu-latest
    name: Docker Build|Push
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Build|Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile_path }}
          push: ${{ inputs.push }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.docker_repository_name }}:latest