name: .Net Test

on:
  workflow_call:
    inputs:
      line_rate_thresholds:
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    name: CI Test
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: app_build

    - name: Test
      run: dotnet test ${{ github.workspace }}/EventOrganizer.Test.dll --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: ${{ inputs.line_rate_thresholds }}

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
