name: .NET Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    name: .NET Build
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore